# 0 = "off"
# 1 = "warn"
# 2 = "error"

env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:unicorn/all
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/electron
  - plugin:import/typescript
  - plugin:solid/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
  - solid
ignorePatterns:
  - src/config.ts

rules:
  #region eslint
  comma-dangle: [2, never]
  semi: [2, never]
  #endregion

  #region @typescript-eslint
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-unused-vars': [
    1,
    {
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_'
    }
  ]
  #endregion

  #region unicorn
  unicorn/filename-case: 0
  unicorn/no-empty-file: 0
  unicorn/no-keyword-prefix: 0
  unicorn/no-null: 0
  unicorn/numeric-separators-style: 0
  unicorn/prevent-abbreviations: 0
  #endregion

settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .cts  # TODO remove
      - .tsx
      - .d.ts
  import/resolver:
    typescript: # eslint-import-resolver-typescript
      alwaysTryTypes: true # always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`