# 0 = "off"
# 1 = "warn"
# 2 = "error"

env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:unicorn/all
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/electron
  - plugin:import/typescript
  - plugin:solid/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
  - solid

rules:
  #region eslint
  comma-dangle: [2, never]
  semi: [2, never]
  #endregion

  #region unicorn
  unicorn/no-empty-file: 0
  unicorn/no-keyword-prefix: 0
  unicorn/no-null: 0
  unicorn/prevent-abbreviations: 0
  #endregion
