let APP_MAP: Config = {
  SO: {
    'CCleaner <VERSION> Portable': {
      url: 'https://www.fcportables.com/ccleaner-portable',
      urlTmp: 'https://www.softpedia.com/get/Security/Secure-cleaning/CCleaner.shtml',
      version: '6.19.10858',
      website: 'FCPortables',
    },
    'OpenVPN <VERSION>': {
      url: 'https://www.softpedia.com/get/Security/Security-Related/OpenVPN.shtml',
      version: '2.6.6',
      download: 'https://swupdate.openvpn.org/community/releases/OpenVPN-<VERSION>-amd64.msi',
      versionOptions: {
        evaluate: '"<VERSION>".split(" ").join("-")',
      },
      website: 'Softpedia',
    },
    'TomVPN <VERSION> Portable': {
      url: 'https://www.fcportables.com/tomvpn-portable',
      version: '2.3.8',
      website: 'FCPortables',
    },
    'NirSoft WifiInfoView <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Network-Tools/Misc-Networking-Tools/WifiInfoView.shtml',
      version: '2.80',
      download: 'https://www.nirsoft.net/utils/wifiinfoview-x64.zip',
      website: 'Softpedia',
    },
    'NirSoft WirelessNetView <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Network-Tools/Network-Monitoring/WirelessNetView.shtml',
      download: 'https://www.nirsoft.net/utils/wirelessnetview.zip',
      version: '1.75',
      website: 'Softpedia',
    },
    'NirSoft ShellMenuNew <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/System/OS-Enhancements/ShellMenuNew.shtml',
      download: 'https://www.nirsoft.net/utils/shellmenunew.zip',
      version: '1.02',
      website: 'Softpedia',
    },
    'NirSoft SmartSniff <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Network/Portable-SmartSniff.shtml',
      download: 'https://www.nirsoft.net/utils/smsniff-x64.zip',
      version: '2.29',
      website: 'Softpedia',
    },
    'NirSoft HashMyFiles <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/System/File-Management/HashMyFiles.shtml',
      download: 'https://www.nirsoft.net/utils/hashmyfiles-x64.zip',
      version: '2.44',
      website: 'Softpedia',
    },
    'HWMonitor <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/System-Info/Portable-HWMonitor.shtml',
      download: 'https://download.cpuid.com/hwmonitor/hwmonitor_<VERSION>.zip',
      version: '1.51.0',
      versionOptions: {
        evaluate: '"<VERSION>".split(".").slice(0,3).join("-")',
      },
      website: 'Softpedia',
    },
    'NTLite <VERSION>': {
      url: 'https://www.softpedia.com/get/System/OS-Enhancements/NTLite.shtml',
      download: 'https://downloads.ntlite.com/files/NTLite_setup_x64.exe',
      id: 248365,
      version: '2023.6.9292',
      website: 'Softpedia',
    },
    'WHDownloader <VERSION>': {
      url: 'https://www.softpedia.com/get/System/System-Miscellaneous/Windows-Hotfix-Downloader.shtml',
      id: 235948,
      childNumber: 1,
      version: '0.0.2.5',
      website: 'Softpedia',
    },
    'WinToolkit <VERSION>': {
      url: 'https://www.softpedia.com/get/System/OS-Enhancements/Windows-7-Toolkit.shtml',
      id: 181550,
      childNumber: 2,
      version: '2.0.6276.30646',
      website: 'Softpedia',
    },
    'MSMG Toolkit <VERSION>': {
      url: 'https://www.softpedia.com/get/Tweak/System-Tweak/MSMG-ToolKit.shtml',
      urlTmp: 'https://msmgtoolkit.in/downloads.html',
      id: 256326,
      childNumber: 2,
      version: '13.4',
      website: 'Softpedia',
    },
    'Process Explorer <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/System/System-Info/Process-Explorer.shtml',
      urlTmp1: 'https://portableapps.com/apps/utilities/process-explorer-portable',
      urlTmp2: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/System-Info/Process-Explorer-Portable.shtml',
      download: 'https://download.sysinternals.com/files/ProcessExplorer.zip',
      version: '17.04',
      website: 'Softpedia',
    },
    'CrystalDiskInfo <VERSION> Portable': {
      url: 'https://portableapps.com/apps/utilities/crystaldiskinfo_portable',
      download: 'https://download2.portableapps.com/portableapps/CrystalDiskInfoPortable/CrystalDiskInfoPortable_<VERSION>.paf.exe',
      version: '9.2.1',
      website: 'PortableApps',
    },
    'Universal Extractor 2 RC 3 Portable': {
      owner: 'Bioruebe',
      repo: 'UniExtract2',
      assetNumber: 0,
      version: '2.0.0 RC 3',
      website: 'GitHub',
    },
    'LockHunter <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/System/File-Management/LockHunter.shtml',
      urlTmp: 'https://lockhunter.com/download.htm',
      download: 'https://lockhunter.com/assets/exe/lockhuntersetup_portable_<VERSION>.exe',
      versionOptions: {
        evaluate: '"<VERSION>".split(".").slice(0,3).join("-")',
      },
      version: '3.4.3.146',
      website: 'Softpedia',
    },
    'Microsoft Activation Scripts <VERSION>': {
      download: 'https://github.com/massgravel/Microsoft-Activation-Scripts/archive/refs/heads/master.zip',
      owner: 'massgravel',
      repo: 'Microsoft-Activation-Scripts',
      version: '1.5',
      website: 'GitHub',
    },
    'IObit Driver Booster Pro <VERSION> Portable': {
      url: 'https://www.fcportables.com/driver-boost-portable',
      version: '11.0.0.21',
      website: 'FCPortables',
    },
    'Geek Uninstaller <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Tweak/Uninstallers/Geek-Uninstaller-Portable.shtml',
      download: 'https://download2.portableapps.com/portableapps/GeekUninstallerPortable/GeekUninstallerPortable_<VERSION>.paf.exe',
      version: '1.5.1.162',
      website: 'Softpedia',
    },
    'Revo Uninstaller Pro <VERSION> Portable': {
      url: 'https://www.fcportables.com/revo-uninstaller-pro-portable',
      version: '5.1.7',
      website: 'FCPortables',
    },
    'HWiNFO64 <VERSION> Portable': {
      url: 'https://portableapps.com/apps/utilities/hwinfo-portable',
      download: 'https://download2.portableapps.com/portableapps/HWiNFOPortable/HWiNFOPortable_<VERSION>_English.paf.exe',
      version: '7.50.5150',
      website: 'PortableApps',
    },
    'XAMPP <VERSION>': {
      url: 'https://www.softpedia.com/get/Internet/Servers/Server-Tools/XAMPP.shtml',
      urlTmp: 'https://www.apachefriends.org/index.html',
      download: 'https://netcologne.dl.sourceforge.net/project/xampp/XAMPP%20Windows/<VERSION>/xampp-windows-x64-<VERSION>-0-VS16-installer.exe',
      id: 32107,
      childNumber: 2,
      version: '8.2.4',
      website: 'Softpedia',
    },
    'AIDA64 Engineer Edition <VERSION> Portable': {
      url: 'https://www.fcportables.com/aida64-portable',
      version: '6.90.6500',
      website: 'FCPortables',
    },
    'Mozilla Thunderbird <VERSION> Portable': {
      url: 'https://portableapps.com/apps/internet/thunderbird_portable',
      download: 'https://download2.portableapps.com/portableapps/ThunderbirdPortable/ThunderbirdPortable_<VERSION>_English.paf.exe',
      version: '102.13.0',
      website: 'PortableApps',
    },
    'IObit Uninstaller PRO <VERSION> Portable': {
      url: 'https://www.fcportables.com/iobit-uninstaller-portable',
      version: '13.1.0.3',
      website: 'FCPortables',
    },
    'UltraISO Premium Edition <VERSION> Portable': {
      url: 'https://www.fcportables.com/ultraiso-premium-portable',
      version: '9.7.6.3860',
      website: 'FCPortables',
    },
    'TeamViewer <VERSION>': {
      url: 'https://www.softpedia.com/get/Internet/Remote-Utils/TeamViewer-Portable.shtml',
      urlTmp: 'https://www.filecatchers.com/teamviewer-portable',
      comment: 'filecatchers PORTABLE IS NOT UPDATED',
      download: 'https://download.teamviewer.com/download/TeamViewerPortable.zip',
      version: '15.42.5',
      website: 'Softpedia',
    },
    'Cheat Engine <VERSION>': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Gaming-Related/Cheat-Engine.shtml',
      urlTmp: 'https://github.com/cheat-engine/cheat-engine/releases/latest',
      id: 258418,
      childNumber: 2,
      version: '7.5',
      website: 'Softpedia',
    },
    'Fan Control Portable': {
      owner: 'Rem0o',
      repo: 'FanControl.Releases',
      assetNumber: 0,
      version: '174',
      website: 'GitHub',
    },
    'WinSCP <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Internet/FTP-Clients/Portable-WinSCP.shtml',
      download: 'https://deac-fra.dl.sourceforge.net/project/winscp/WinSCP/<VERSION>/WinSCP-<VERSION>-Portable.zip',
      id: 79107,
      version: '6.2.3',
      website: 'Softpedia',
    },
  },
  Downloader: {
    'Crunchyroll Downloader <VERSION> Portable': {
      owner: 'hama3254',
      repo: 'Crunchyroll-Downloader-v3.0',
      assetNumber: 0,
      version: '3',
      website: 'GitHub',
    },
    'qBittorrent <VERSION> Portable': {
      url: 'https://portableapps.com/apps/internet/qbittorrent_portable',
      version: '4.6.4',
      download: 'https://download2.portableapps.com/portableapps/qBittorrentPortable/qBittorrentPortable_<VERSION>.paf.exe',
      website: 'PortableApps',
    },
    'JDownloader 2 (r<VERSION>) Portable': {
      owner: 'EIGHTFINITE',
      repo: 'jdownloader-portable',
      assetNumber: 0,
      urlTmp: 'https://codecpack.co/download/JDownloader-Portable.html',
      download: 'https://github.com/EIGHTFINITE/jdownloader-portable/archive/refs/tags/<VERSION>.zip',
      version: '17241',
      website: 'GitHub',
    },
    'youtube-dl-gui <VERSION> Portable': {
      owner: 'murrty',
      repo: 'youtube-dl-gui',
      assetNumber: 1,
      tagNumber: 1,
      download: 'https://github.com/murrty/youtube-dl-gui/releases/download/<VERSION>/youtube-dl-gui.zip',
      version: '3.3.0',
      website: 'GitHub',
    },
    'yt-dlp <VERSION> Portable': {
      owner: 'yt-dlp',
      repo: 'yt-dlp',
      assetNumber: 15,
      version: '2024.03.10',
      website: 'GitHub',
    },
    'WSL2 Distro Manager <VERSION> Portable': {
      owner: 'bostrot',
      repo: 'wsl2-distro-manager',
      assetNumber: 1,
      version: '1.8.11',
      website: 'GitHub',
    },
  },
  Media: {
    'Audacity <VERSION> Portable': {
      url: 'https://portableapps.com/apps/music_video/audacity_portable',
      download: 'https://download2.portableapps.com/portableapps/AudacityPortable/AudacityPortable_<VERSION>.paf.exe',
      version: '3.4.2',
      website: 'PortableApps',
    },
    'mkvalidator <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Multimedia/Video/Other-VIDEO-Tools/mkvalidator.shtml',
      urlTmp: 'https://www.matroska.org/downloads/mkvalidator.html',
      download: 'https://netix.dl.sourceforge.net/project/matroska/mkvalidator/mkvalidator-<VERSION>-win64.zip',
      id: 182912,
      childNumber: 1,
      version: '0.6.0',
      website: 'Softpedia',
    },
    'MKVToolNix <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Multimedia/Video/Portable-MKVToolnix.shtml',
      download: 'https://mkvtoolnix.download/windows/releases/<VERSION>/mkvtoolnix-64-bit-<VERSION>.7z',
      versionOptions: {
        evaluate: '"<VERSION>".split(".").slice(0,2).join(".")',
      },
      version: '81.0.0',
      website: 'Softpedia',
    },
    'MKVExtractGUI <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Multimedia/Video/Other-VIDEO-Tools/MKVExtractGUI-2.shtml',
      urlTmp: 'http://sourceforge.net/projects/mkvextractgui-2',
      download: 'https://kumisystems.dl.sourceforge.net/project/mkvextractgui-2/MKVExtractGUI-<VERSION>.zip',
      id: 182912,
      childNumber: 1,
      version: '2.4.0.0',
      website: 'Softpedia',
    },
    'Blackmagic Design DaVinci Resolve Studio + Neat Video <VERSION> Portable': {
      url: 'https://www.fcportables.com/davinci-resolve-portable',
      version: '18.5.1.0006',
      website: 'FCPortables',
    },
    'Inviska MKV Extract <VERSION> Portable': {
      url: 'https://www.videohelp.com/software/Inviska-MKV-Extract',
      download: 'https://www.videohelp.com/download/Inviska_MKV_Extract_<VERSION>_x86-64_Portable.7z',
      version: '11.0',
      website: 'VideoHelp',
    },
    'Rhinoceros <VERSION> Portable': {
      url: 'https://www.fcportables.com/rhino-portable',
      version: '7.17.22102.05001',
      website: 'FCPortables',
    },
    'Spotify <VERSION> Portable': {
      url: 'https://www.filecatchers.com/spotify-windows-portable',
      version: '1.2.25.1011',
      website: 'FileCatchers',
    },
    'Topaz Gigapixel AI <VERSION> Portable': {
      url: 'https://www.fcportables.com/topaz-gigapixel-portable',
      version: '6.3.3',
      website: 'FCPortables',
    },
    'FFmpeg Batch Converter <VERSION> Portable': {
      url: 'https://www.filecatchers.com/ffmpeg-batch-portable',
      urlTmp: 'https://ffmpeg-batch.sourceforge.io',
      version: '2.8.1',
      website: 'FileCatchers',
    },
    'mp3DirectCut <VERSION> Portable': {
      url: 'https://www.filecatchers.com/mp3directcut-portable',
      version: '2.36',
      website: 'FileCatchers',
    },
    'MKV Muxing Batch GUI <VERSION> Portable': {
      url: 'https://www.filecatchers.com/mkv-muxing-batch-portable',
      version: '2.3',
      website: 'FileCatchers',
    },
    'CorelDRAW Graphics Suite <VERSION> Portable': {
      url: 'https://www.fcportables.com/coreldraw-suite-portable',
      version: '24.4.0.625',
      website: 'FCPortables',
    },
    'LosslessCut <VERSION> Portable': {
      urlTmp: 'https://www.filecatchers.com/losslesscut-portable',
      owner: 'mifi',
      repo: 'lossless-cut',
      assetNumber: 11,
      version: '3.46.2',
      website: 'GitHub',
    },
    'VLC <VERSION> Portable': {
      url: 'https://portableapps.com/apps/music_video/vlc_portable',
      urlTmp1: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Multimedia/Video/Portable-VLC-Media-Player.shtml',
      urlTmp2: 'https://www.filecatchers.com/vlc-portable',
      download: 'https://download2.portableapps.com/portableapps/VLCPortable/VLCPortable_<VERSION>.paf.exe',
      version: '3.0.20',
      website: 'PortableApps',
    },
  },
  Office: {
    'Foxit PDF Editor Pro <VERSION> Portable': {
      url: 'https://www.fcportables.com/foxit-pdf-editor-portable',
      version: '2023.1.0.15510',
      website: 'FCPortables',
    },
    'WinMerge <VERSION> Portable': {
      url: 'https://portableapps.com/apps/utilities/winmerge_portable',
      urlTmp1: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/File-management/Windows-Portable-Applications-Portable-WinMerge.shtml',
      urlTmp2: 'https://www.fcportables.com/winmerge-portable',
      download: 'https://download2.portableapps.com/portableapps/WinMergePortable/WinMergePortable_<VERSION>.paf.exe',
      version: '2.16.30',
      website: 'PortableApps',
    },
    'WinRAR <VERSION>': {
      url: 'https://www.softpedia.com/get/Compression-tools/WinRAR.shtml',
      download: 'https://www.rarlab.com/rar/winrar-x64-<VERSION>.exe',
      versionOptions: {
        evaluate: '"<VERSION>".split(".").join("")',
      },
      version: '6.24',
      website: 'Softpedia',
    },
    '7-Zip <VERSION> Portable': {
      url: 'https://www.filecatchers.com/7zip-portable',
      version: '23.01',
      website: 'FileCatchers',
    },
    'Bulk Rename Utility <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/File-management/Portable-Bulk-Rename-Utility.shtml',
      download: 'https://www.s3.tgrmn.com/bru/BRU_NoInstall.zip',
      version: '3.4.4.0',
      website: 'Softpedia',
    },
  },
  Emulator: {
    'MEmu <VERSION>': {
      url: 'https://www.softpedia.com/get/Mobile-Phone-Tools/Others/MEmu.shtml',
      download: 'https://dl.memuplay.com/download/Memu-Setup.exe',
      version: '9.0.2',
      website: 'Softpedia',
    },
    'PSPSPP <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Other-Portable-Applications/PPSSPP-Portable.shtml',
      download: 'https://www.ppsspp.org/files/<VERSION>/ppsspp_win.zip',
      versionOptions: {
        evaluate: '"<VERSION>".split(".").join("_")',
      },
      version: '1.15.4',
      website: 'Softpedia',
    },
    'NoxPlayer <VERSION>': {
      url: 'https://www.softpedia.com/get/Mobile-Phone-Tools/Others/Nox-APP-Player.shtml',
      download: 'https://en.bignox.com/en/download/fullPackage',
      version: '7.0.5.8',
      website: 'Softpedia',
    },
    NSC_Builder: {
      owner: 'julesontheroad',
      repo: 'NSC_BUILDER',
      assetNumber: 1,
      version: '1.01b',
      website: 'GitHub',
    },
    'JoyToKey <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/Tweak/System-Tweak/JoyToKey.shtml',
      download: 'https://joytokey.net/download/JoyToKeySetup_en.exe',
      version: '6.9.1.535',
      website: 'Softpedia',
    },
    'X360CE <VERSION> Portable': {
      url: 'https://www.x360ce.com',
      download: 'https://www.x360ce.com/files/x360ce.zip',
      owner: 'x360ce',
      repo: 'x360ce',
      assetNumber: 1,
      comment: 'LATEST GITHUB RELEASE IS OUTDATED',
      version: '4.17.15.0',
      website: 'GitHub',
    },
  },
  DB: {
    'Robo 3T <VERSION> Portable': {
      url: 'https://www.softpedia.com/get/PORTABLE-SOFTWARE/Database-Utils/Portable-Robo-3T.shtml',
      urlTmp: 'https://github.com/Studio3T/robomongo/releases/latest',
      version: '1.4.4',
      website: 'Softpedia',
      websiteTmp: 'GitHub',
    },
    'Studio 3T <VERSION>': {
      url: 'https://www.softpedia.com/get/Internet/Servers/Database-Utils/Studio-3T.shtml',
      downloadTmp: 'https://download.studio3t.com/studio-3t/windows/<VERSION>/studio-3t-x64.zip',
      versionOptions: {
        evaluate: '"<VERSION>"',
      },
      version: '2023.5.0',
      website: 'Softpedia',
    },
  },
  Games: {
    'TEKKEN 7: Ultimate Edition': {
      url: 'https://fitgirl-repacks.site/tekken-7-ultimate-edition',
      version: '4.22',
    },
  },
}

export default APP_MAP